routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return redirect('login');
});

Auth::routes(['register' => false]);
Route::get('redirect/{driver}', 'Auth\LoginController@redirectToProvider')->name('login.provider');
Route::get('{driver}/callback', 'Auth\LoginController@handleProviderCallback')->name('login.callback');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'super_admin','middleware' => ['auth','roles:super_admin']], function () {
    Route::get('/', 'SuperAdminController@index')->name('super_admin.index');
    Route::resource('user', 'UserController');
});

Route::group(['prefix' => 'admin','middleware' => ['auth','roles:admin']], function () {
    Route::get('/', 'AdminController@index')->name('admin.index');
});

Route::group(['prefix' => 'operator','middleware' => ['auth','roles:operator']], function () {
    Route::get('/', 'OperatorController@index')->name('operator.index');
});

Route::group(['middleware' => ['auth','roles:user']], function () {
    Route::get('booking/search', 'BookingController@search')->name('booking.search');
    Route::get('booking/order/{id}', 'BookingController@order')->name('booking.order');
    Route::post('booking/get_type_price', 'BookingController@getTypePrice')->name('booking.get_type_price');
    Route::post('booking/store', 'BookingController@store')->name('booking.store');
    Route::get('booking/success', 'BookingController@success')->name('booking.success');
    Route::get('parking/report', 'ParkingController@report')->name('parking.report');
    Route::resource('parking', 'ParkingController');
});

resources/views/layouts/partials/header.blade.php
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="index.html" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{{ asset('assets/images/logo-sm-dark.png') }}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{{ asset('assets/images/logo-dark.png') }}" alt="" height="19">
                    </span>
                </a>

                <a href="index.html" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{{ asset('assets/images/logo-sm-light.png') }}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{{ asset('assets/images/logo-light.png') }}" alt="" height="19">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm mr-2 font-size-16 d-lg-none header-item waves-effect waves-light" data-toggle="collapse" data-target="#topnav-menu-content">
                <i class="fa fa-fw fa-bars"></i>
            </button>

            <!-- App Search-->
            <form class="app-search d-none d-lg-block">
                <div class="position-relative">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="mdi mdi-magnify"></span>
                </div>
            </form>
        </div>

        <div class="d-flex">

            <div class="dropdown d-inline-block d-lg-none ml-2">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-search-dropdown"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="mdi mdi-magnify"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0"
                    aria-labelledby="page-header-search-dropdown">

                    <form class="p-3">
                        <div class="form-group m-0">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit"><i class="mdi mdi-magnify"></i></button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <div class="dropdown d-none d-lg-inline-block ml-1">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                    <i class="mdi mdi-fullscreen"></i>
                </button>
            </div>


            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect" id="page-header-notifications-dropdown"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="mdi mdi-bell-outline"></i>
                    <span class="badge badge-danger badge-pill">1</span>
                </button>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right p-0"
                    aria-labelledby="page-header-notifications-dropdown">
                    <div class="p-3">
                        <div class="row align-items-center">
                            <div class="col">
                                <h6 class="m-0 font-weight-medium text-uppercase"> Notifications </h6>
                            </div>
                            <div class="col-auto">
                                <span class="badge badge-pill badge-danger">New 1</span>
                            </div>
                        </div>
                    </div>
                    <div data-simplebar style="max-height: 230px;">
                        <a href="" class="text-reset notification-item">
                            <div class="media">
                                <div class="avatar-xs mr-3">
                                    <span class="avatar-title bg-primary rounded-circle font-size-16">
                                        <i class="mdi mdi-cart"></i>
                                    </span>
                                </div>
                                <div class="media-body">
                                    <h6 class="mt-0 mb-1">Your order is placed</h6>
                                    <div class="font-size-12 text-muted">
                                        <p class="mb-1">If several languages coalesce the grammar</p>
                                        <p class="mb-0"><i class="mdi mdi-clock-outline"></i> 3 min ago</p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="p-2 border-top">
                        <a class="btn-link btn btn-block text-center" href="javascript:void(0)">
                            <i class="mdi mdi-arrow-down-circle mr-1"></i> Load More..
                        </a>
                    </div>
                </div>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    @if (!empty(Auth::user()->photo))
                    <img class="rounded-circle header-profile-user" src="{{ Auth::user()->photo }}"
                    alt="Header Avatar">
                    @endif

                    <span class="d-none d-sm-inline-block ml-1">{{ Auth::user()->name }}</span>
                    <i class="mdi mdi-chevron-down d-none d-sm-inline-block"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <!-- item-->
                    <a class="dropdown-item" href="#"><i class="mdi mdi-face-profile font-size-16 align-middle mr-1"></i> Profile</a>
                    <a class="dropdown-item" href="#"><i class="mdi mdi-account-settings font-size-16 align-middle mr-1"></i> Settings</a>
                    <div class="dropdown-divider"></div>
                    {{-- <a class="dropdown-item" href="#"><i class="mdi mdi-logout font-size-16 align-middle mr-1"></i> Logout</a> --}}
                    <a class="dropdown-item" href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                        <i class="mdi mdi-logout font-size-16 align-middle mr-1"></i> Logout
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div>
            </div>
        </div>
    </div>
</header>

resources/views/layouts/partials/items.blade.php
<div class="topnav">
    <div class="container-fluid">
        <nav class="navbar navbar-light navbar-expand-lg topnav-menu">

            <div class="collapse navbar-collapse" id="topnav-menu-content">
                <ul class="navbar-nav">
                    {{-- item untuk super_admin --}}
                    @if (Auth::user()->roles == 'super_admin')
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/home') }}">
                            <i class="mdi mdi-storefront mr-2"></i>Dashboard
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="lahan_parkir" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="mdi mdi-cloud-print-outline mr-2"></i>Lahan Parkir  <div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="lahan_parkir">
                            <a href="{{ route('parking.index') }}" class="dropdown-item">Data</a>
                            <a href="{{ route('parking.report') }}" class="dropdown-item">Report</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="users" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="mdi mdi-cloud-print-outline mr-2"></i>Users<div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="users">
                            <a href="{{ route('user.index') }}" class="dropdown-item">Data</a>
                        </div>
                    </li>

                    {{-- item untuk admin --}}
                    @elseif(Auth::user()->roles == 'admin')
                    <li class="nav-item">
                        <a class="nav-link" href="index.html">
                            <i class="mdi mdi-storefront mr-2"></i>Dashboard
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="lahan_parkir" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="mdi mdi-cloud-print-outline mr-2"></i>Lahan Parkir  <div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="lahan_parkir">
                            <a href="calendar.html" class="dropdown-item">Data</a>
                            <a href="calendar.html" class="dropdown-item">Report</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="users" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="mdi mdi-cloud-print-outline mr-2"></i>Users<div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="users">
                            <a href="calendar.html" class="dropdown-item">Data</a>
                            <a href="calendar.html" class="dropdown-item">Report</a>
                        </div>
                    </li>
                    {{-- item untuk operator --}}
                    @elseif(Auth::user()->roles == 'operator')
                    <li class="nav-item">
                        <a class="nav-link" href="index.html">
                            <i class="mdi mdi-storefront mr-2"></i>Dashboard
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="lahan_parkir" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="mdi mdi-cloud-print-outline mr-2"></i>Lahan Parkir  <div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="lahan_parkir">
                            <a href="calendar.html" class="dropdown-item">Data</a>
                            <a href="calendar.html" class="dropdown-item">Report</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle arrow-none" href="#" id="users" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="mdi mdi-cloud-print-outline mr-2"></i>Users<div class="arrow-down"></div>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="users">
                            <a href="calendar.html" class="dropdown-item">Data</a>
                            <a href="calendar.html" class="dropdown-item">Report</a>
                        </div>
                    </li>
                    {{-- item untuk user --}}
                    @elseif(Auth::user()->roles == 'user')
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/home') }}">
                            <i class="mdi mdi-book mr-2"></i>Booking
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('parking.index') }}">
                            <i class="mdi mdi-ticket-confirmation mr-2"></i>Pesanan
                        </a>
                    </li>
                    @endif
                </ul>
            </div>
        </nav>
    </div>
</div>